# Generated by Django 3.1.4 on 2021-01-04 12:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('duration', models.DurationField()),
                ('place', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('video_size', models.IntegerField(blank=True)),
                ('durations', models.DurationField()),
                ('author', models.CharField(blank=True, max_length=20)),
                ('formations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='home.formations')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=40)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('imageprofil', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('birthdate', models.DateField(auto_now=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('formation', models.ManyToManyField(related_name='users', to='home.Formations')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.users')),
            ],
        ),
    ]
