# Generated by Django 3.1.4 on 2021-01-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210105_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forums',
        ),
    ]
