# Generated by Django 3.1.4 on 2021-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_forums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='recipient',
            new_name='recipient_id',
        ),
        migrations.RenameField(
            model_name='inbox',
            old_name='transmitter',
            new_name='transmitter_id',
        ),
        migrations.AddField(
            model_name='inbox',
            name='date_of_receipt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='sending_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='answers',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='messages',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
