# Generated by Django 3.1.4 on 2021-01-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210107_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='inbox',
            old_name='transmitter_id',
            new_name='transmitter',
        ),
    ]
