# Generated by Django 3.1.4 on 2021-01-13 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210107_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('name', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=40)),
                ('testimonials', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='inbox',
            name='sending_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
