# Generated by Django 3.1.4 on 2021-01-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210113_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='sending_date',
            field=models.DateField(auto_now=True),
        ),
    ]
