# Generated by Django 3.1.4 on 2021-01-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210113_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='date_of_receipt',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='name',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='users',
            field=models.ManyToManyField(related_name='testimonials', to='home.Users'),
        ),
        migrations.AddField(
            model_name='users',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
