# Generated by Django 3.1.4 on 2021-01-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210113_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='users',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.users'),
        ),
    ]
